### ISSUE TITLE
map issue

### ISSUE THREAD

**Issue by glistenlau** [aerisweather/AerisAndroidSDK#1]
Hello, 

I tried the demo app, everything works fine except the interactive map, when I click it in the drawer, the app stopped, and I got the error below:

```
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime: FATAL EXCEPTION: main
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime: Process: com.example.demoaerisproject, PID: 15717
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.UiSettings com.google.android.gms.maps.GoogleMap.getUiSettings()' on a null object reference
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at com.hamweather.aeris.maps.AerisMapView.init(AerisMapView.java:219)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at com.example.fragment.MapFragment.onCreateView(MapFragment.java:61)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.app.Fragment.performCreateView(Fragment.java:2053)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.app.BackStackRecord.run(BackStackRecord.java:834)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-20 11:03:54.613 15717-15717/com.example.demoaerisproject E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Can you help me to solve this problem?

**Comment by sshie** [comment]
Hello Yi - It's great to hear that you were able to solve the issue!

**Comment by glistenlau** [comment]
The issue is solved after I update my google play service, now it works great!
