### ISSUE TITLE
Null Point Exception

### ISSUE THREAD

**Issue by geetves** [aerisweather/AerisAndroidSDK#2]
Hello,
I have setup this demo app on android studio. I am using google play services latest version.  When I run the app, it works perfectly until I click on "Interactive Maps" option, the app crashes. Below is the error:

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.hamweather.aeris.tiles.AerisTile com.hamweather.aeris.maps.AerisMapOptions.getTile()' on a null object reference
                                                                                  at com.example.fragment.MapFragment.initMap(MapFragment.java:166)
                                                                                  at com.example.fragment.MapFragment.onActivityCreated(MapFragment.java:102)
                                                                                  at android.app.Fragment.performActivityCreated(Fragment.java:2072)
                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                  at android.app.BackStackRecord.run(BackStackRecord.java:846)
                                                                                  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1473)
                                                                                  at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
                                                                                  at android.os.Handler.handleCallback(Handler.java:810)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                  at android.os.Looper.loop(Looper.java:189)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5528)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
`

Can you please help me to solve this issue.

Thanks,
Geet

**Comment by sshie** [comment]
This is resolved with the 2.0.0 version, which is currently in beta.
