### ISSUE TITLE
sometimes throws exception when aeris map initiallize

### ISSUE THREAD

**Issue by Patrick7893** [aerisweather/AerisAndroidSDK#9]
Hi!
Sometimes i get an exception when aeris map is initializing:
```
E/AerisTileProvider: Only the original thread that created a view hierarchy can touch its views.
                                                                           android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                               at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6892)
                                                                               at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1048)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.support.v4.widget.DrawerLayout.requestLayout(DrawerLayout.java:1265)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.view.View.requestLayout(View.java:19781)
                                                                               at android.widget.TextView.checkForRelayout(TextView.java:7368)
                                                                               at android.widget.TextView.setText(TextView.java:4480)
                                                                               at android.widget.TextView.setText(TextView.java:4337)
                                                                               at android.widget.TextView.setText(TextView.java:4312)
                                                                               at com.aerisweather.aeris.maps.AnimationControlView.setTitleAndTime(AnimationControlView.java:95)
                                                                               at com.aerisweather.aeris.tiles.AerisTileProvider.loadTimeResponse(AerisTileProvider.java:115)
                                                                               at com.aerisweather.aeris.tiles.AerisTileProvider.getTile(AerisTileProvider.java:84)
                                                                               at com.google.android.gms.maps.model.zzs.getTile(Unknown Source)
                                                                               at com.google.android.gms.maps.model.internal.zzaa.onTransact(Unknown Source)
                                                                               at android.os.Binder.transact(Binder.java:499)
                                                                               at com.google.android.gms.maps.model.internal.ab.a(:com.google.android.gms.DynamiteModulesB:7)
                                                                               at com.google.android.gms.maps.model.al.a(:com.google.android.gms.DynamiteModulesB:5)
                                                                               at com.google.maps.api.android.lib6.gmm6.api.ag.run(:com.google.android.gms.DynamiteModulesB:14)
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:761)
```

Exception throws when i change fragment of my app in absolutely random order. I tried to catch exception in my code, but cant find place where it throws

**Comment by sshie** [comment]
Hi Pavel,

Thanks for the issue report. I've forwarded your message to the helpdesk so that our support folks can get involved and assist you.

Thanks!

**Comment by Patrick7893** [comment]
Oh, and one more. How can i hide legend layer in AerisMapContainerView?

**Comment by sshie** [comment]
From the animation container view, you can get access to the three legend views:

`
ampLegendsImageView = (ImageView) findViewById(id.ivLegend);

pointsLegendsImageView = (ImageView) findViewById(id.ivPointLegend);

polyLegendsImageView = (ImageView) findViewById(id.ivPolyLegend);
`

Thanks for the great question, we've tagged this as an item for a future update where we'll provide methods to hide and show the legend views to make this easier. 

Thanks!
